version: '3.8'

services:
  app:
    build: .
    container_name: bookmark-manager
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    entrypoint: >
      /bin/sh -c "
      mkdir -p /app/instance &&
      chmod 777 /app/instance &&
      python app.py" 